---
title: "Connect"
---
## Prospective students, postdocs, and collaborators
Students who are interested in internship opportunities are welcome to get in touch with a CV and a transcript of records. Contact me directly at solveig.aamlid@polytechnique.edu for potential PhD project and postdoc opportunities. If you are interested in collaborating on any of the topics I am working on you are welcome to send me a quick description of what is on your mind!


## Contact and profiles

- **Email:** solveig.aamlid@polytechnique.edu
- [Google Scholar](https://scholar.google.com/citations?user=zQqxVgUAAAAJ)
- [ORCID](hhttps://orcid.org/0000-0002-7788-9974)
- [LinkedIn](https://www.linkedin.com/in/solveig-stubmo-aamlid-a6635896/)
- [ResearchGate](https://www.researchgate.net/profile/Solveig-Aamlid)
- [PMC Laboratoire de Physique de la Matière Condensée](https://pmc.polytechnique.fr/)


## Address École Polytechnique

UMR7643 Laboratoire de Physique de la Matière Condensée 
École Polytechnique  
Route de Saclay
91128 Palaiseau cedex, France
